### ISSUE TITLE
Can't understand Burgers example 

### ISSUE THREAD

**Issue by baggepinnen** [jborggaard/QQR#2]
Hello and thanks for providing this repo!

I'm trying to walk through the last example in the paper. but the code appears to have some inconsistencies. The line:
https://github.com/jborggaard/QQR/blob/114151dd8f41c5947ac2651c15f8256fd3ca99b5/examples/Burgers1DControl/hjbBurgers1D.m#LL18C5-L18C5
is missing one input argument, and the matrix `N` it computes does not have the dimension $n \times n^2$, it has the dimensions $n \times n$. The function `AlbrechtQQR` called a few lines below does not appear to be present in this repo?

**Comment by jborggaard** [comment]
Thank you.  There definitely is an issue with this.  I'll update a corrected version in a day.
